name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Sync frontend to S3
        run: aws s3 sync frontend/ s3://cloud-portfolio-frontend/ --delete

      - name: Sync expense tracker
        run: aws s3 sync projects/expense-tracker/ s3://cloud-portfolio-frontend/projects/expense-tracker/ --exclude "*.zip" --exclude "*.py"

      - name: Sync weather dashboard
        run: aws s3 sync projects/weather-dashboard/ s3://cloud-portfolio-frontend/projects/weather-dashboard/ --exclude "*.zip" --exclude "*.py"

      - name: Sync Linux quiz
        run: aws s3 sync projects/Ci-Quiz-App/CI-Quiz-App/ s3://cloud-portfolio-frontend/projects/linux-quiz/

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id EJNQOYSHP4HLB --paths "/*"
